### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by mikemtzp** [indigodavid/dasik-band-events#2]
### Suggestions ♻️
- Set the font size bigger for all the sections within the desktop version so the site is more readable

### Highlights 💯
- ✔️Excelent styling
- ✔️Great applied use of the template for a real-case website
- ✔️Great animations

**Keep up doing excellent work!** 👍

**Comment by indigodavid** [comment]
Thanks for the suggestion, the latest implementation includes this change. Best regards
